-- | Compile-time proof that the runtime cohort's public library surfaces can
-- coexist in one component. Runtime calls live in @Main@; empty imports here
-- retain the remaining direct package edges.
module LinkProof.Imports () where

import Database.PostgreSQL.Migrate ()
import Database.PostgreSQL.Migrate.CLI ()
import Database.PostgreSQL.Migrate.Embed ()
import Database.PostgreSQL.Migrate.History.Codd ()
import Database.PostgreSQL.Migrate.History.HasqlMigration ()
import EphemeralPg ()
import Kafka.Effectful ()
import Kafka.Producer ()
import Kafka.Streamly.Stream ()
import Keiki.Codec.JSON ()
import Keiki.Core ()
import Keiro.Command ()
import Keiro.Migrations ()
import Keiro.PGMQ ()
import Keiro.Schema ()
import Kiroku.Cli ()
import Kiroku.Metrics.Config ()
import Kiroku.Otel.TraceContext ()
import Kiroku.Store.Migrations ()
import OpenTelemetry.Exporter.InMemory ()
import OpenTelemetry.Exporter.OTLP ()
import OpenTelemetry.Propagator.W3CTraceContext ()
import OpenTelemetry.SDK ()
import OpenTelemetry.SemanticConventions ()
import Pgmq.Config ()
import Pgmq.Hasql.Sessions ()
import Shibuya.Adapter.Kafka.Config ()
import Shibuya.Adapter.Kiroku ()
import Shibuya.Adapter.Pgmq.Config ()
import Shibuya.App ()
import Shibuya.Metrics.Config ()
